name: container
on: push

jobs:
    node-docker:
        runs-on: ubuntu-latest
        container:
            image: rushmash/gcc-arm-embedded-docker:latest 
        steps:
            - name: Log the node version
              run: |
                  cmake --version
